// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1X844SfAKK_Srn2FFdZKJ6EnIAYnaIHs',
    appId: '1:259294538826:web:9e615b32da9fe323e9cab3',
    messagingSenderId: '259294538826',
    projectId: 'chatappfirebase-e6c68',
    authDomain: 'chatappfirebase-e6c68.firebaseapp.com',
    storageBucket: 'chatappfirebase-e6c68.appspot.com',
    measurementId: 'G-TBFP8BJYKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRqCFgTLdjHeyfB1tiHQt9cR4dDSZ7vr0',
    appId: '1:259294538826:android:b9468ca605b156b6e9cab3',
    messagingSenderId: '259294538826',
    projectId: 'chatappfirebase-e6c68',
    storageBucket: 'chatappfirebase-e6c68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT_1a-Fk4Hvez8MxF6K4idEzElRy_Hy78',
    appId: '1:259294538826:ios:3b1ca119a4484c49e9cab3',
    messagingSenderId: '259294538826',
    projectId: 'chatappfirebase-e6c68',
    storageBucket: 'chatappfirebase-e6c68.appspot.com',
    iosBundleId: 'com.chatapp.chatappFirebase',
  );
}
