// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCayTU6HHzucZCs_PIyK-vN1GYLwKuZtrg',
    appId: '1:524809105744:web:fbc7c79737a8e652ef7c55',
    messagingSenderId: '524809105744',
    projectId: 'the-last-wish-36ce8',
    authDomain: 'the-last-wish-36ce8.firebaseapp.com',
    storageBucket: 'the-last-wish-36ce8.appspot.com',
    measurementId: 'G-TV9BSGSLPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZedYPABMQkjFijT7UNSPXP525mmH6RkQ',
    appId: '1:524809105744:android:46859278cf4897d6ef7c55',
    messagingSenderId: '524809105744',
    projectId: 'the-last-wish-36ce8',
    storageBucket: 'the-last-wish-36ce8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALl4ZzBCl6-sm_mxsWOk62-_YedHOGnEg',
    appId: '1:524809105744:ios:694fc700f33c8efdef7c55',
    messagingSenderId: '524809105744',
    projectId: 'the-last-wish-36ce8',
    storageBucket: 'the-last-wish-36ce8.appspot.com',
    iosClientId: '524809105744-e0219f8f119j4tl9ntbtbfibr4tc6sta.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseParctice',
  );
}
